bin/pip install flask
bin/pip install flask-login
bin/pip install flask-openid
bin/pip install flask-mail
bin/pip install flask-sqlalchemy
bin/pip install sqlalchemy-migrate
bin/pip install flask-whooshalchemy
bin/pip install flask-wtf
bin/pip install flask-babel
bin/pip install guess_language
bin/pip install flipflop
bin/pip install coverage
